Post about uncertainties
borglab/gtsam.org pull request #40
Opened 2021-02-07 21:51 UTC by mmattamala

Hi @dellaert 

I wrote this post based on the discussions we had in the gtsam-user groups about the uncertainties. I tried to cover almost all the topics we discussed, and creating figures to support the sections.

Let me know your comments, I'll be happy to address any concern. I will also ask the people here at DRS to get more feedback.

Additionally, there was one technical issue with Latex integration I couldn't solve: using the `\cancel{}` command. I checked everything locally to see if things looked good, but I couldn't make that one work.

Thanks!

2021-02-08 21:29 UTC, dellaert reviewed
Wow @mmattamala ! This looks amazing. I think this could be published as is, although I would some time to fully read. This leads me to two main comments/suggestions that would help me:

1) it's long :-) Perhaps this could be split into a part with linear/nonlinear, and a part with manifolds.
2) more controversial/involved: in GTSAM I deliberately use |h(x)-z|, not |z-h(x)|. Then linearization is |x0+H dx-z| = |H dx - (z-x0)|. I noticed you are going the other way :-)

I have not read the post in detail yet, it's something I noticed and wanted to start a conversation. You worked on this for a long time, and I'm on board to publish as is (after I read in detail). But the above might help people grok everything.

2021-02-08 21:35 UTC, mmattamala commented on _posts/2021-02-07-uncertainties.md
> +However, we now that in reality things do not work that way, and we will usually have errors produced by noise in our sensors. The most common way to address this problem is adding some *zero-mean Ga
Just fixed, thanks for noticing this :)

2021-02-08 21:44 UTC, mmattamala commented
Hi @dellaert , glad to know that you liked it!

Regarding the comments:
1. I'm happy to split it if it works better. I guess we would need a summary at the end to the first part to connect to the next.
2. I can change the residual as you mentioned to be consistent, it's an easy fix but it must be done carefully.

I'm looking forward to any other comments or suggestions, I really hope the post helps :)

2021-02-08 22:28 UTC, jlblancoc commented
Amazing work, Matias!

I'm also more used to see h(x)-z, which also doesn't flip the sign of the
observation function Jacobian. Just a convention, but I think it's slightly
more convenient.... plus, it's the one used in the library! :-)

2021-02-08 23:45 UTC, dellaert commented
cool, re-request a review then I’ll get pinged.

2021-02-09 11:54 UTC, mmattamala commented
Thanks a lot @jlblancoc and @dellaert 

I'd like to ask you a question I thought it could be relevant to add in the "linear and nonlinear" part:

**Do you have any idea on how the covariance estimate gets affected when we use Levenberg-Marquardt?** Because the damping is changing the Hessian, hence the covariance estimate should be different.

I know that apart from the convergence behaviour, LM can help when we have some ill-conditions in the problem, and that sometimes work as an "easy fix". But I'm afraid that when we want to extract the covariance as well, it will get over/underestimated (I have not tested it but perhaps you have :) ). 

It may be useful to mention that "issue", and that instead of just changing the optimizer to solve ill-conditions, it's better to check the jacobians or adding explicit prior factors to improve the system but still having some control on our uncertainty about the variables. What do you think?

2021-02-09 12:35 UTC, dellaert commented
LM just finds a minimum. Covariance calculations are based on non-damped Jacobians. But, you should never use LM to “abide” an ill-posed problem in the first place :-)

2021-02-12 19:08 UTC, michaelbosse requested changes
In general I believe this is a very good and detailed write up.  I just have some comments that address distinctions between groups and manifolds.

2021-02-12 19:08 UTC, michaelbosse commented on _posts/2021-02-07-uncertainties-part2.md
> +We also showed how the right-hand convention is related to how the composition is defined when working with manifolds, such as rigid-body transformations and rotation matrices. The  **local** and **r
should be "... when working with *groups*"

It would be good to the concepts for manipulating transformations, ie generating odometry factors, distinct from representing uncertainty on these group objects.   For poses in gtsam both are very similar and use a right handed convention, but understanding their distinction can help with applying these ideas and understanding a variety of nonlinear objects used in gtsam such  as unit vectors, nav states (pose + velocity),  camera calibration matrices, etc.

2021-02-13 12:01 UTC, mmattamala commented
Thanks a lot for the comments @michaelbosse 

I read them carefully and will update the post to be more clear about the distinctions you mentioned. I think the trickiest part is to keep the differences clear so as to understand when each concept applies (uncertainties for manifolds, frame conventions for groups, adjoints for Lie groups)

2021-02-13 14:03 UTC, dellaert commented
Thanks Mike!!
Matias, the following document, which is more implementation oriented, might also help, maybe you could link to it: https://gtsam.org/notes/GTSAM-Concepts.html

2021-02-14 16:00 UTC, mmattamala commented
Hi @dellaert 

Thanks for the previous explanation on LM and the "Concepts" post.
I updated the post after Mike's feedback, as well as José Luis' and your comments. It is a 3 parts post now, I hope it is not a problem :)

- **Part 1, linear and nonlinear:** how we get the covariances from the Hessian
- **Part 2, frames and manifolds:** introduces the reference frames and the operations on groups and manifolds following the frames and the "concepts" post.
- **Part 3, adjoints and covariances:** the adjoint as a way to relate increments on the left and the right (including what Mike mentioned before in his first 2 comments), and Mangelson's formulas compliant with GTSAM.

2021-02-15 23:33 UTC, dellaert approved these changes
Looks amazing to me. Still some small comments, and I attach he rendered pdfs so Mike can approve if he is ok with your changes:
1) in part 1 the "- noise" still feels awkward, and I don't see actually where you need it. You could just say "Ax-b ~ normal"....
2) in part 2 (which is beautiful!) formula 11 renders weirdly for me, with a red "\cancel" in subscript. See attached pdf.

[Reducing the uncertainty about the uncertainties, part 1_ Linear and nonlinear _ GTSAM.pdf](https://github.com/borglab/gtsam.org/files/5984605/Reducing.the.uncertainty.about.the.uncertainties.part.1_.Linear.and.nonlinear._.GTSAM.pdf)

[Reducing the uncertainty about the uncertainties, part 2_ Frames and manifolds _ GTSAM.pdf](https://github.com/borglab/gtsam.org/files/5984604/Reducing.the.uncertainty.about.the.uncertainties.part.2_.Frames.and.manifolds._.GTSAM.pdf)

[Reducing the uncertainty about the uncertainties, part 3_ Adjoints and covariances _ GTSAM.pdf](https://github.com/borglab/gtsam.org/files/5984595/Reducing.the.uncertainty.about.the.uncertainties.part.3_.Adjoints.and.covariances._.GTSAM.pdf)

2021-02-16 01:12 UTC, johnwlambert commented on _posts/2021-02-07-uncertainties-part1.md
> +First point to note here is that finding the solution $\mathcal{X}^{*}$ requires to invert the matrix $\mathbf{A}^{T} \Sigma^{-1} \mathbf{A}$, which in general is hard since it can be huge and dense
Very nice post @mmattamala. One small typo here in spelling of the authors' names

2021-02-16 01:24 UTC, johnwlambert commented on _posts/2021-02-07-uncertainties-part1.md
> +In our [next post](https://gtsam.org/2021/02/07/uncertainties-part2.html) we will review how these ideas generalize when we are not estimating *vector* variables anymore but other objects such as rot
perhaps a small typo here: "no only in the maths" -> "not only in the maths"

2021-02-16 01:33 UTC, johnwlambert commented on _posts/2021-02-07-uncertainties-part2.md
> +Since in GTSAM the extrinsic calibration is defined the other way to be consitent with the right-hand convention, i.e $\mathbf{T}_{WC}$, the implementation of the `CalibratedCamera` handles it by [pr
Another nice post! Small typo here "consitent" -> "consistent"

2021-02-16 11:26 UTC, mmattamala commented on _posts/2021-02-07-uncertainties-part1.md
> +First point to note here is that finding the solution $\mathcal{X}^{*}$ requires to invert the matrix $\mathbf{A}^{T} \Sigma^{-1} \mathbf{A}$, which in general is hard since it can be huge and dense
Thanks John for the comment and proofreading!

2021-02-16 11:52 UTC, mmattamala commented
Thanks a lot @dellaert and @johnwlambert for your feedback!

Frank, regarding your comments:
1. Yeah, I see your point with the "negative noise". I just wanted to make the manipulation explicit since it's the same we do later but it looks odd indeed. Another approach would be to isolate it such as keep it positive, but when we define the factor we can swap the model and the measurement as usual to keep your convention (because it's more convenient).
2. In part 2, now I figured out how to solve the problem by adding a macro in the MathJax configuration.

2021-02-17 00:38 UTC, michaelbosse commented on _posts/2021-02-07-uncertainties-part2.md
> +**That is what makes working with manifolds so convenient**: All the constraints that are part of the definition of the object are naturally handled, and we can work in tangent vector spaces using th
Calibration matrices *are* in fact groups ;-)   See https://en.wikipedia.org/wiki/Triangular_matrix

Perhaps use the example of Unit Vectors as a non-group object (which is still a manifold)

2021-02-17 01:11 UTC, michaelbosse commented on _posts/2021-02-07-uncertainties-part2.md
> +1. **Local**: An operation that maps elements from the manifold to the tangent space $\mathbf{\xi} = \text{local}(\mathbf{T})$
This single parameter version of **local** assumes the existence of an Identity object, which is only true for groups.
The more general local operation takes the difference between two objects and expresses it as a vector in the tangent space of one

2021-02-17 01:11 UTC, michaelbosse commented on _posts/2021-02-07-uncertainties-part2.md
> +2. **Retract or retraction**: The opposite operation: mapping from the tangent space back to the manifold $\mathbf{T} = \text{retract}(\mathbf{\xi})$.
Likewise, the more general retract operations needs the input of the manifold object from which the tangent space is referenced from.

It looks like you are prematurely trying to make manifolds looks like lie groups.  Where as you could instead explain it as  we  have objects with differentiable properties (manifolds) and objects with composition/inverse/identity properties (groups), and when they have both we get Lie groups.  (where the retract and local operations are conveniently defined with respect to the group Identity).

Also please stress that groups are not needed for most of GTSAM.     Its just that when the manifold object are also groups, we can express the local and retract operations with respect to the identity object.

2021-02-21 15:14 UTC, mmattamala commented on _posts/2021-02-07-uncertainties-part2.md
> +**That is what makes working with manifolds so convenient**: All the constraints that are part of the definition of the object are naturally handled, and we can work in tangent vector spaces using th
Great, thanks for clarifying this and the example with the unit vectors :)

2021-02-21 15:14 UTC, mmattamala commented on _posts/2021-02-07-uncertainties-part2.md
> +1. **Local**: An operation that maps elements from the manifold to the tangent space $\mathbf{\xi} = \text{local}(\mathbf{T})$
I changed the notation a bit to make this more explicit.

2021-02-21 15:19 UTC, mmattamala commented on _posts/2021-02-07-uncertainties-part2.md
> +2. **Retract or retraction**: The opposite operation: mapping from the tangent space back to the manifold $\mathbf{T} = \text{retract}(\mathbf{\xi})$.
Thanks for pointing this out. I hope this new version more explicit and consistent with GTSAM.
Now Lie groups should mainly be important in the part 3 only, when we use the adjoint to transform covariances.

2021-02-21 15:20 UTC, mmattamala commented on _posts/2021-02-07-uncertainties-part2.md
> +so we can apply the transformation on the left-hand side:
I added an explanation in part 3, when we talk about covariance transformations, to explicitly mention this case and how it's related to the adjoint

2021-02-21 15:21 UTC, mmattamala commented on _posts/2021-02-07-uncertainties-part2.md
> +The main difference with Lie groups is that by using the general concept of [_retraction_](https://press.princeton.edu/absil) we can use **alternative definitions to go from the tangent space to the
I added a paragraph to explain this as well.

2021-02-21 15:21 UTC, mmattamala commented on _posts/2021-02-07-uncertainties-part2.md
> +<br />
Solved in part 3 I hope

2021-02-23 04:53 UTC, dellaert commented
Ready to go?

2021-02-23 11:13 UTC, mmattamala commented
Yes, thanks Frank!

2021-02-23 17:13 UTC, michaelbosse commented
Could someone post the updated pdfs again so I can quickly see the changes?

2021-02-23 17:18 UTC, mmattamala commented
Hi Mike, here you go. Thanks for your help!

[Reducing the uncertainty about the uncertainties, part 1_ Linear and nonlinear _ GTSAM.pdf](https://github.com/borglab/gtsam.org/files/6030673/Reducing.the.uncertainty.about.the.uncertainties.part.1_.Linear.and.nonlinear._.GTSAM.pdf)

[Reducing the uncertainty about the uncertainties, part 2_ Frames and manifolds _ GTSAM.pdf](https://github.com/borglab/gtsam.org/files/6030674/Reducing.the.uncertainty.about.the.uncertainties.part.2_.Frames.and.manifolds._.GTSAM.pdf)

[Reducing the uncertainty about the uncertainties, part 3_ Adjoints and covariances _ GTSAM.pdf](https://github.com/borglab/gtsam.org/files/6030677/Reducing.the.uncertainty.about.the.uncertainties.part.3_.Adjoints.and.covariances._.GTSAM.pdf)

2021-02-23 17:32 UTC, dellaert commented
I'll await Mike's OK and then merge after I make sure it renders well. Then I'll tweet massively about it, and you should re-tweet and get others to re-tweet :-) Alternatively, *you* can tweet and I'll ret-tweet. I would recommend making a small tweet-storm with the skinny, as not many people will actually take the time to go to the blog itself without that "teaser" material.

2021-02-23 22:30 UTC, michaelbosse commented
Overall this reads much better!

Just some minor nits:
- Eqns 29+30, Part II, and Eqns 17+24, Part III are too long and get clipped by the page width.
- I'm not sure we need to specify the same frame as a prefix and suffix for tangent space vectors; seems redundant since they are both always the same.  IMHO the extra symbols unnecessarily clutter the equations making it harder to see the elegance in the math.
- The latest release of GTSAM doesn't default to S0(3)xR^3 anymore but rather showed that SE(3) converges better in optimizations for minimal (if any) performance loss.

2021-02-23 23:35 UTC, mmattamala commented
Awesome, thanks a lot for going through the whole thing! I'll make the last changes tomorrow morning (in UK time):

- I'll see if I can change the equations a bit to fit the space; I know that in the website there should appear a scroll bar to get access to the whole expression, but I'd like to know if @dellaert has a better suggestion.
- Yeah, I agree that makes the expressions more cluttered and thanks for pointing that out. I'll stay with the prefix for the vectors to be consistent with previous parts (like the camera example)
- I think it's better if I just remove that part in which I mention SO(3) X R^3 to not make things more complicated if GTSAM simply uses the exponential map for that.

After that I guess we can agree the post should be ready for Frank to check how it renders and we start the tweet-storm :)

2021-02-24 00:57 UTC, mmattamala commented
@dellaert I ended up fixing it now, so feel free to check how it renders and proceed :)

2021-02-24 01:08 UTC, jlblancoc commented
1 sec! I was just about to post my two cents... ;-) 

[1st part](https://drive.google.com/file/d/1S6BG-wn18twatZ4ONRZLDXAGzzBSTaWW/view?usp=sharing)

(more to come)

2021-02-24 01:12 UTC, mmattamala commented
@jlblancoc haha great! we can postpone this a bit to give you more time and check your comments carefully, thanks a lot.

2021-02-24 01:46 UTC, jlblancoc commented
[2nd part](https://drive.google.com/file/d/1SHrumZ_4U27eD7VIQ6SUUZ1ARJOF-IPV/view?usp=sharing)

@mmattamala  thank you for undertaking the ambitious task of explaining this material! Legions of future students will thank you ;-)

2021-02-24 02:26 UTC, jlblancoc commented
And the last one: [3rd part](https://drive.google.com/file/d/1SJOrY_0x-2zpduf-VHLPnyRgTWi5dq8Q/view?usp=sharing)

Congrats, it's an excellent material, I really believe in the need to visually express all these concepts with pictures... a *must read* for GTSAM users, and PhD students in our field in general.

2021-02-24 20:40 UTC, mmattamala commented
Thanks a lot @jlblancoc ! I really appreciate your words :D
I think I addressed all your comments, I've attached the PDFs.

@dellaert I think it's ready, feel free to do the final check.

[Reducing the uncertainty about the uncertainties, part 1_ Linear and nonlinear _ GTSAM.pdf](https://github.com/borglab/gtsam.org/files/6038686/Reducing.the.uncertainty.about.the.uncertainties.part.1_.Linear.and.nonlinear._.GTSAM.pdf)

[Reducing the uncertainty about the uncertainties, part 2_ Frames and manifolds _ GTSAM.pdf](https://github.com/borglab/gtsam.org/files/6038710/Reducing.the.uncertainty.about.the.uncertainties.part.2_.Frames.and.manifolds._.GTSAM.pdf)

[Reducing the uncertainty about the uncertainties, part 3_ Adjoints and covariances _ GTSAM.pdf](https://github.com/borglab/gtsam.org/files/6038688/Reducing.the.uncertainty.about.the.uncertainties.part.3_.Adjoints.and.covariances._.GTSAM.pdf)

2021-02-25 12:50 UTC, dellaert commented
I checked it on my mac and it renders well, so i'll merge. Amazing series of posts!

2021-02-25 12:50 UTC, merged