Fix custom factor math...
borglab/gtsam.org pull request #50
Opened 2022-01-25 21:23 UTC by dellaert

... and 99.9996 percentage

2022-01-25 21:27 UTC, dellaert commented
Fixes #48

2022-01-25 21:27 UTC, dellaert commented
@gchenfc pls approve and merge unless you see issues.

2022-01-25 22:00 UTC, gchenfc requested changes
See https://github.com/borglab/gtsam/pull/1064

2022-01-25 22:00 UTC, gchenfc commented on _tutorials/intro.html
> +<div class="standard" id='magicparlabel-65581'>We can optimize this factor graph as before, by creating an initial estimate of type <em><b>Values</b></em>, and creating and running an optimizer. The
These **3-sigma** covariance ellipses in 2D indicate the marginal over position, over all possible orientations, and show the area which contain 99.9996% of the probability mass.

2022-01-30 19:13 UTC, gchenfc approved these changes

2022-01-30 19:14 UTC, merged